### PR TITLE
Revert "Fix extra fancy code blocks"

### PR DESCRIPTION
**Pull request by cmwinters**
Reverts primer/primer-markdown#65

Going to fix this directly from github/github

### CODE REVIEW

**Comment by shurcooL** [comment]
If we're not supposed to modify README.md directly in this repository (as I understand from your comment, its canonical source is in another repo), perhaps this is worth noting in [this repo's CONTRIBUTING.md](https://github.com/primer/primer-markdown/blob/master/.github/CONTRIBUTING.md), so that people in the future don't make the same mistake.

**Comment by broccolini** [comment]
@shurcooL We're in the process of moving Primer out of github/github and pulling in as a package again, and we're also working on updating the documentation website. In the mean time things are a bit out of date and confusing, sorry, but this will be rectified soon.

**Comment by shurcooL** [comment]
No problem, if you're already tracking this, no need to do anything extra. I just wanted to suggest the above in case it's helpful.

**Comment by broccolini** [comment]
Thanks @shurcooL - appreciate the feedback and looking forward to making Primer easier to contribute to in future.

**Pull request merged**
